apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: test
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: rancher/hello-world
        imagePullPolicy: IfNotPresent
        args:
        - localhost:80
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld
    app.kubernetes.io/instance: k8sfiles
  name: helloargo
  namespace: test
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: helloworld
  type: NodePort